# Generated by Django 5.2.dev20240704183052 on 2024-09-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_sub_entry_type_subentry_subentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
