# Generated by Django 5.2.dev20240704183052 on 2024-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_journalentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
