# Generated by Django 5.2.dev20240704183052 on 2024-08-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
